### ISSUE TITLE
Footer is broken on trac

### ISSUE THREAD

**Issue by dingo-d** [WordPress/wporg-mu-plugins#123]
Seems like on Trac pages the footer is skipping the rest of the content and gets rendered right after the header

<img width="1809" alt="image (1)" src="https://user-images.githubusercontent.com/8638515/150974833-839db251-fea8-4206-a5bd-0f6650b216e0.png">
<img width="1141" alt="image" src="https://user-images.githubusercontent.com/8638515/150974836-216e697e-1864-4097-b140-72ef6f3c4366.png">

**Comment by iandunn** [comment]
I saw this initially, but it started working when I did a hard refresh. I think @dd32 bumped the cachebuster already, but there's a delay between when we update the templates in SVN and when those changes get deployed.

I still see `#altlinks` being pushed down into the footer. That can be solved by adding `overflow: auto` to `#main`, and maybe some `bottom-padding` too.

**Comment by ryelle** [comment]
I'm still seeing the issue in the screenshot. Since the content is hidden when the reports popup appears, the footer shrinks up to the content, and overlaps the report links. Adding a `z-index:1` to `#report-popup` fixes that.

**Comment by ryelle** [comment]
In 49e85195beb1a54df4b6c71e18444eec5ae78a62 I added `clear: both` to the footer itself to fix these issues with floating content - there's no reason we'll want to float the footer, and that should handle any other edge cases. It does not add any spacing though, so the link does sit right on top of the footer.

<img width="1013" alt="Screen Shot 2022-01-25 at 6 22 21 PM" src="https://user-images.githubusercontent.com/541093/151076369-2ded83b4-68ed-41c2-9b81-3afe9bd0fcc3.png">

**Comment by dingo-d** [comment]
Yup, still happens for me after a hard cache clear

<img width="1032" alt="image" src="https://user-images.githubusercontent.com/8638515/151136771-ccf14030-6e81-4b1f-a3e1-defb3b7d17d8.png">

Also, I've noticed a JS error in the console

```js
Uncaught ReferenceError: wporgGlobalHeaderI18n is not defined
    at wporg-global-header-script.js?ver=1642529040:178:48
```

<img width="644" alt="image" src="https://user-images.githubusercontent.com/8638515/151136907-6c0981f3-c576-422e-bf99-1e4bf08b29b9.png">

**Comment by ryelle** [comment]
I've fixed the reports alignment & the footer overlay in [11477-meta](https://meta.trac.wordpress.org/changeset/11477/), but I think it will need a hard refresh, I'm not sure where to change the cachebuster on for this stylesheet.

I also pushed a fix for the JS error, 3c470c36942d0867a821a0b6a152c248f954796f, but the real cause of the problem there is that the templates need to be synced.

**Comment by iandunn** [comment]
> not sure where to change the cachebuster on for this stylesheet.

I'm not either, but I'm guessing it's either 61a597266f95ca6ac69eb86e9cbb6663f22c338d or  https://meta.trac.wordpress.org/browser/sites/trunk/trac.wordpress.org/templates/wporg-head.html

**Comment by dd32** [comment]
Normally this wouldn't have been a problem, as Trac would've continued to load the old CSS, but, the CSS isn't being served by the CDN so the newer CSS was loaded with the old template.

Trac templates are static, and are not automatically updated.

I've run `php update-headers.php` and commited the result in: https://meta.trac.wordpress.org/changeset/11478

Simplest way to update Trac is to checkout `https://meta.svn.wordpress.org/sites/trunk/trac.wordpress.org/templates/` directly, run the script, commit the resulting changes.

**Comment by ryelle** [comment]
I bumped the CSS cache in [11482-meta](https://meta.trac.wordpress.org/changeset/11482) & the templates have been rebuilt, so the footer + popup positioning issue is fixed.

**Comment by dingo-d** [comment]
The tickets page of the core trac is still broken for me, not sure if this is due to caching 🤷🏼‍♂️ 

<img width="2211" alt="image" src="https://user-images.githubusercontent.com/8638515/151532362-a2685b30-d795-421b-a66c-8f3967b0a7da.png">

**Comment by ryelle** [comment]
@dingo-d Is the menu still blocking the links? It's expected that the footer collapses up _under_ the modal, I didn't restyle the whole modal.

**Comment by dingo-d** [comment]
Oh, that's a modal! 😅 

I never really noticed the little X on the side.

In that case, it makes sense 👍🏼 And it's not blocking the links 🎉 

Thanks!
